project:
  type: manuscript
  output-dir: .
  resources:
    - "_*.qmd"

manuscript:
  article: capstone.qmd

format: 
  html:
    output-file: index    # Render as index.html
    theme:
      light: lightly
      dark: darkly
